
run-mosquitto-docker:
	docker-compose up -d mosquitto-server

# env:Path += ";C:\Program Files\LOVE\"
run-windows:
	powershell.exe "love.exe . 1"
	powershell.exe "love.exe . 2"
	powershell.exe "love.exe . 3"
	powershell.exe "love.exe . 4"
	powershell.exe "love.exe . 5"
	powershell.exe "love.exe . 6"
	powershell.exe "love.exe . 7"
	powershell.exe "love.exe . 8"
	powershell.exe "love.exe . 9"
	powershell.exe "love.exe . 10"
	powershell.exe "love.exe . 11"
	powershell.exe "love.exe . 12"
	powershell.exe "love.exe . 13"
	powershell.exe "love.exe . 14"
	powershell.exe "love.exe . 15"
	powershell.exe "love.exe . 16"


run-linux:
	love . 1
	love . 2
	love . 3
	love . 4
	love . 5
	love . 6
	love . 7
	love . 8
	love . 9
	love . 10
	love . 11
	love . 12
	love . 13
	love . 14
	love . 15
	love . 16

run-all: run-mosquitto-docker run-windows

