# RUN ON DOCKER CONTAINER
run-raft-all:
	docker-compose up

run-raft-server1:
	docker-compose up raft-server1

run-raft-server2:
	docker-compose up raft-server2

run-raft-server3:
	docker-compose up raft-server3
	
run-tests:
	docker-compose up raft-tests

# # RUN LOCAL
# run-raft:
# 	lua init.lua
