version: "3.9"
services:
  lua-server:
    container_name: lua-server
    image: ubuntu_lua_socket
    command: lua /root/server.lua
    volumes:
      - .:/root
    ports:
      - 8889:8889
  lua-client:
    container_name: lua-client
    image: ubuntu_lua_socket
    command: lua /root/client2.lua lua-server 8888
    volumes:
      - .:/root
  lua-client2:
    container_name: lua-client2
    image: ubuntu_lua_socket
    command: lua /root/client.lua lua-server 8889
    volumes:
      - .:/root