struct { 
    name = "minhaStruct",
    fields = {
        {name = "nome",type = "string"},
        {name = "peso",type = "double"},
        {name = "idade",type = "int"}
    }
}

interface { 
    name = "minhaInt",
    methods = {
        foo = {
            resulttype = "double",
            args = {
                {direction = "in",type = "double"},
                {direction = "in",type = "minhaStruct2"},
                {direction = "in",type = "minhaStruct"},
                {direction = "out",type = "int"}
            }
        }
    }
}