# RUN ON DOCKER CONTAINER
run-server-container:
	docker-compose up lua-server

run-client-container:
	docker-compose up lua-client

# RUN LOCAL
run-server:
	lua server.lua

run-client:
	lua client.lua localhost 8888